{% set name = "yt-astro-analysis" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yt_astro_analysis-{{ version }}.tar.gz
  sha256: f156e7026e98a4422f1e7eb81ff1a1a993207dda63b48b04234c60686ed363b9

build:
  number: 2
  # Keep in sync with pyproject.toml
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - rockstar-galaxies  # [linux]
  host:
    - cython >=3.0.3
    - numpy
    - pip
    - python
  run:
    - h5py >=3.1.0
    - more-itertools >=8.4
    - python
    - yt >=4.0.1
    - rockstar-galaxies  # [linux]

test:
  imports:
    - yt_astro_analysis
    - yt_astro_analysis.cosmological_observation
    - yt_astro_analysis.halo_analysis.halo_finding.rockstar.rockstar_interface  # [linux]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yt-project/yt_astro_analysis
  summary: yt astrophysical analysis modules extension
  dev_url: https://github.com/yt-project/yt_astro_analysis/
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - cphyc
    - brittonsmith
