{% set name = "yt-astro-analysis" %}
{% set version = "1.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://codeload.github.com/cphyc/yt_astro_analysis/tar.gz/refs/heads/fix-rockstar-compilation
  sha256: 330191d302ee8ff68a1ac74152025843d4fd1e86857781f43f8177679c71781f
  fn: yt_astro_analysis-fix-rockstar-compilation.tar.gz

build:
  number: 2
  # Keep in sync with pyproject.toml
  skip: true  # [py<39]
  script: |
    ls
    {{ PYTHON }} -m pip install yt_astro_analysis-fix-rockstar-compilation -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - rockstar-galaxies  # [linux]
  host:
    - cython >=3.0.3
    - numpy
    - pip
    - python
    - setuptools
  run:
    - h5py >=3.1.0
    - more-itertools >=8.4
    - python
    - yt >=4.0.1
    - rockstar-galaxies  # [linux]

test:
  imports:
    - yt_astro_analysis
    - yt_astro_analysis.cosmological_observation
    - yt_astro_analysis.halo_analysis.halo_finding.rockstar.rockstar_interface  # [linux]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yt-project/yt_astro_analysis
  summary: yt astrophysical analysis modules extension
  dev_url: https://github.com/yt-project/yt_astro_analysis/
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - cphyc
    - brittonsmith
